if(WIN32)
    set(ENV{PATH} "${QT_BIN};$ENV{PATH}")
endif()
set(log "${PROGRAM}.txt")
execute_process(COMMAND "${PROGRAM}" -o "${log},txt" RESULT_VARIABLE result)
if(EXISTS "${log}")
    file(READ "${log}" output)
    message("${output}")
endif()
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "SDK test failed: ${result}")
endif()
